FROM golang:1.26.4-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -trimpath \
    -ldflags="-s -w" \
    -o notification \
    ./cmd

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/notification .

EXPOSE 8081

ENTRYPOINT ["./notification"]
